name: uni_hostel_admin
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #
  flutter_svg: ^2.0.7
  #
  get: ^4.6.5
  #
  cupertino_icons: ^1.0.2
  #
  cupertino_stepper: ^0.2.1
  # service locator and di for bloc
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  # Flutter plugin for local db for small data
  shared_preferences: ^2.2.0
  dartz: ^0.10.1
  # for table
  data_table_2: ^2.5.3
  # for responsive text
  auto_size_text: ^3.0.0
  # 
  flutter_web_plugins:
    sdk: flutter
  # use json decode
  freezed: ^2.3.5
  json_serializable: ^6.5.4
  json_annotation: ^4.8.1
  # for api
  http: ^1.1.0
  dio: ^4.0.6
  retrofit: ^3.3.1
  # fleshbar
  another_flushbar: ^1.12.30
  # for file uplload
  image_picker: ^1.0.4
  file_picker: ^5.3.2
  # for tab controller
  buttons_tabbar: ^1.3.7+1
  #
  animated_custom_dropdown: ^1.5.0
  dropdown_button2: ^2.3.7
  # for animation
  animate_do: ^3.0.2
  intl: ^0.18.1
  # for network image cache
  cached_network_image: ^3.2.3
  # for text scrolling
  text_scroll: ^0.2.0
   # used url launcher
  url_launcher: ^6.1.12
  # buttons for web 
  flutter_web_buttons: ^0.0.8
  #
  bottom_sheet: ^4.0.0
  # for loading widget
  loading_animation_widget: ^1.2.0+4
  # for tab bar
  contained_tab_bar_view: ^0.8.0
  # animation for statistics 
  fl_chart: ^0.63.0
  syncfusion_flutter_charts: ^22.2.10
  open_app_file: ^4.0.2

dev_dependencies:
  build_runner: ^2.4.6
  retrofit_generator: any
  flutter_test:
    sdk: flutter
  
  
flutter:
  uses-material-design: true
  

  assets:
    - assets/icons/
    - assets/images/
